backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "works"
    label: "Works"
    folder: "content/works"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "日付", name: "date", widget: "datetime" }
      - { label: "サムネイル", name: "thumbnail", widget: "image" }
      - { label: "説明", name: "description", widget: "text" }
      - { label: "本文", name: "body", widget: "markdown" }
